# Generated by Django 2.0.4 on 2018-04-07 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_address', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('hq_address', models.CharField(max_length=80)),
                ('store_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
