# Generated by Django 2.0.4 on 2018-04-07 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='store_name',
            new_name='name',
        ),
    ]
