# Generated by Django 2.0.4 on 2018-04-08 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('store', '0002_auto_20180407_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_no', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Branch')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Purchase_history')),
            ],
        ),
    ]
